Zach/res
potassco/anthem pull request #101
Opened 2024-04-27 15:30 UTC by ZachJHansen

2024-04-27 19:49 UTC, teiesti requested changes
Very nice! Thanks a lot for assembling this!

I have some comments though:
1. We need newlines at the end of all files.
2. I'd rather put all examples directly into `res` instead of the subfolder `examples` or do you intend to add other resources.
3. Should we distinguish between examples for strong and external equivalences and put them into different folders?
4. I don't like the names `ex1`, ... Do we have more telling names?

2024-04-27 19:53 UTC, teiesti commented
Further question: Are these examples from papers? If so, can we reference them in a way?

2024-04-27 23:43 UTC, ZachJHansen commented
I added a section to the overleaf documentation listing the problems and referencing which papers (if any) in which they originally appeared

2024-05-03 15:13 UTC, teiesti approved these changes

2024-05-03 15:13 UTC, merged