Zach/manual
potassco/anthem pull request #157
Opened 2024-11-11 17:15 UTC by ZachJHansen

2024-11-20 11:06 UTC, teiesti requested changes
Very nice work.

2024-11-20 11:06 UTC, teiesti commented on Dockerfile
I have never used Docker and I am wondering if such a file should go into an entirely new repository. At least that is how I've seen it done with other deployment methods in other project.

That said, I am not opposed to this change. I trust your decision.

2024-11-20 11:06 UTC, teiesti commented on Dockerfile
> +RUN chmod +x /usr/bin/anthem
Once we've published our crate to crates.io, installing the current stable version of anthem is as simple as `cargo install anthem`. I think, we should use this here.

2024-11-20 11:06 UTC, teiesti commented on res/manual/src/installation.md
> +    cp anthem/target/release/anthem /usr/bin/
Two things:
1. It is not wise to manually install executables to `/usr/bin/` because this folder is usually managed by the system's package manager. Install to `/usr/local/bin` instead.
2. Installing software to a subdirectory of `/usr` makes it available to all users of a system and therefore requires root privileges. Thus, this method might not work for all our users. The much safer option is to install to `~/.local/bin`.

2024-11-20 11:06 UTC, teiesti commented on res/manual/src/installation.md
> +    chmod +x /usr/bin/anthem
I don't think that is necessary because the file creates by cargo is already executable.

2024-11-20 11:06 UTC, teiesti commented on Dockerfile
Update: After thinking about it, we could also put deployment methods into separate branches. When creating such a branch I'd use the [`--orphan` flag](https://graphite.dev/guides/git-orphan-branches).

2024-11-21 20:52 UTC, ZachJHansen commented on Dockerfile
Our resident Docker expert suggested it should go in the root of the project we wish to containerize (e.g. the root of anthem's source code). As for the separate branch idea, I'm not really sure what the advantages/disadvantages are. We could discuss tomorrow.

2024-11-21 20:54 UTC, ZachJHansen commented
Thanks for looking this over! I implemented your comments and re-submitted the PR. 

Best,
Zach

> On Nov 20, 2024, at 5:06 AM, Tobias Stolzmann ***@***.***> wrote:
> 
> 
> @teiesti requested changes on this pull request.
> 
> Very nice work.
> 
> On Dockerfile <https://github.com/potassco/anthem/pull/157#discussion_r1850074820>:
> 
> I have never used Docker and I am wondering if such a file should go into an entirely new repository. At least that is how I've seen it done with other deployment methods in other project.
> 
> That said, I am not opposed to this change. I trust your decision.
> 
> In Dockerfile <https://github.com/potassco/anthem/pull/157#discussion_r1850078147>:
> 
> > +RUN apt install -y git
> +RUN apt-get install -y vim
> +
> +# Install Rust and Cargo
> +RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
> +
> +# Install Vampire v4.9 (statically linked)
> +RUN wget https://github.com/vprover/vampire/releases/download/v4.9casc2024/vampire
> +RUN mv vampire /usr/bin/
> +RUN chmod +x /usr/bin/vampire
> +
> +# Install Anthem
> +RUN git clone https://github.com/potassco/anthem.git
> +RUN cd anthem && . "$HOME/.cargo/env" && cargo build --release
> +RUN cp anthem/target/release/anthem /usr/bin/
> +RUN chmod +x /usr/bin/anthem
> Once we've published our crate to crates.io, installing the current stable version of anthem is as simple as cargo install anthem. I think, we should use this here.
> 
> In res/manual/src/installation.md <https://github.com/potassco/anthem/pull/157#discussion_r1850098780>:
> 
> > @@ -0,0 +1,25 @@
> +# Installing From Crates.io
> +tbd
> +
> +# Installing From Source
> +Linux users can build `anthem` directly from source, as follows.
> +
> +```
> +    git clone https://github.com/potassco/anthem.git && cd anthem
> +    cargo build --release
> +    cp anthem/target/release/anthem /usr/bin/ 
> Two things:
> 
> It is not wise to manually install executables to /usr/bin/ because this folder is usually managed by the system's package manager. Install to /usr/local/bin instead.
> Installing software to a subdirectory of /usr makes it available to all users of a system and therefore requires root privileges. Thus, this method might not work for all our users. The much safer option is to install to ~/.local/bin.
> In res/manual/src/installation.md <https://github.com/potassco/anthem/pull/157#discussion_r1850100160>:
> 
> > @@ -0,0 +1,25 @@
> +# Installing From Crates.io
> +tbd
> +
> +# Installing From Source
> +Linux users can build `anthem` directly from source, as follows.
> +
> +```
> +    git clone https://github.com/potassco/anthem.git && cd anthem
> +    cargo build --release
> +    cp anthem/target/release/anthem /usr/bin/ 
> +    chmod +x /usr/bin/anthem
> I don't think that is necessary because the file creates by cargo is already executable.
> 
> On Dockerfile <https://github.com/potassco/anthem/pull/157#discussion_r1850109000>:
> 
> Update: After thinking about it, we could also put deployment methods into separate branches. When creating such a branch I'd use the --orphan flag <https://graphite.dev/guides/git-orphan-branches>.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/potassco/anthem/pull/157#pullrequestreview-2448245799>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AGKMMRZONS4ZYSUVXPF7ZNT2BRUMVAVCNFSM6AAAAABRSIYJ6CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINBYGI2DKNZZHE>.
> You are receiving this because you authored the thread.
>

2024-11-21 23:48 UTC, teiesti commented on Dockerfile
If your resident Docker expert says so, I am fine with it.

2024-11-22 14:27 UTC, teiesti approved these changes

2024-11-22 14:27 UTC, merged