Add more, hopefully rather uncontroversial simplifications
potassco/anthem pull request #172
Opened 2024-12-04 22:31 UTC by teiesti

This is the first follow-up for #164. It groups all the "easy" and therefore rather "uncontroversial" simplifications.

2024-12-04 22:32 UTC, teiesti commented
@ZachJHansen You can review and merge this whenever you like. I do not indent to add more to this. All other simplifications will go into other PRs.

2024-12-05 16:32 UTC, ZachJHansen requested changes
Looks good overall, except I would prefer that each change in apply_definitions be a separate function so we can choose to apply them independently. Also, it would be nice to support a transformation from "F -> #false" to "not F" as well.

2025-01-31 16:00 UTC, teiesti commented
We discussed in today's joint meeting:
1. We split `apply_definitions` into `apply_negation_definition`, `apply_implication_definition` and `apply_equivalence_definition`.
2. We add the inverse of each of these functions, e.g. `apply_negation_definition_inverse`.

2025-02-04 20:03 UTC, ZachJHansen approved these changes
I double-checked that these are all intuitionistically valid and they seem fine. We should carefully enumerate all the simplifications in the system description though, just to be safe.

2025-02-04 20:03 UTC, merged